// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.0
// source: api/ingest.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       [][]byte               `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_api_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_api_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *PushRequest) GetRecords() [][]byte {
	if x != nil {
		return x.Records
	}
	return nil
}

type PushReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      uint64                 `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushReply) Reset() {
	*x = PushReply{}
	mi := &file_api_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushReply) ProtoMessage() {}

func (x *PushReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushReply.ProtoReflect.Descriptor instead.
func (*PushReply) Descriptor() ([]byte, []int) {
	return file_api_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *PushReply) GetAccepted() uint64 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

var File_api_ingest_proto protoreflect.FileDescriptor

const file_api_ingest_proto_rawDesc = "" +
	"\n" +
	"\x10api/ingest.proto\x12\x06ingest\"'\n" +
	"\vPushRequest\x12\x18\n" +
	"\arecords\x18\x01 \x03(\fR\arecords\"'\n" +
	"\tPushReply\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x04R\baccepted28\n" +
	"\x06Ingest\x12.\n" +
	"\x04Push\x12\x13.ingest.PushRequest\x1a\x11.ingest.PushReplyB\x18Z\x16metricshell/inv008/apib\x06proto3"

var (
	file_api_ingest_proto_rawDescOnce sync.Once
	file_api_ingest_proto_rawDescData []byte
)

func file_api_ingest_proto_rawDescGZIP() []byte {
	file_api_ingest_proto_rawDescOnce.Do(func() {
		file_api_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_ingest_proto_rawDesc), len(file_api_ingest_proto_rawDesc)))
	})
	return file_api_ingest_proto_rawDescData
}

var file_api_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_ingest_proto_goTypes = []any{
	(*PushRequest)(nil), // 0: ingest.PushRequest
	(*PushReply)(nil),   // 1: ingest.PushReply
}
var file_api_ingest_proto_depIdxs = []int32{
	0, // 0: ingest.Ingest.Push:input_type -> ingest.PushRequest
	1, // 1: ingest.Ingest.Push:output_type -> ingest.PushReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_ingest_proto_init() }
func file_api_ingest_proto_init() {
	if File_api_ingest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ingest_proto_rawDesc), len(file_api_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ingest_proto_goTypes,
		DependencyIndexes: file_api_ingest_proto_depIdxs,
		MessageInfos:      file_api_ingest_proto_msgTypes,
	}.Build()
	File_api_ingest_proto = out.File
	file_api_ingest_proto_goTypes = nil
	file_api_ingest_proto_depIdxs = nil
}
