#!/usr/bin/env bash
set -Eeuo pipefail
export LC_ALL=C
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")"&&pwd)"; REPO_DIR="$(git -C "$ROOT_DIR" rev-parse --show-toplevel)"; PROTO="$ROOT_DIR/prototype"; RUN_ID="${RUN_ID:-$(date -u +%Y%m%dT%H%M%SZ)}"; RESULTS_DIR="$ROOT_DIR/results/$RUN_ID"; mkdir -p "$RESULTS_DIR"
ASSERTIONS="$RESULTS_DIR/assertions.tsv"; OBSERVATIONS="$RESULTS_DIR/observations.tsv"; SUMMARY="$RESULTS_DIR/summary.tsv"; IMAGE=metricshell-inv015:prototype; CONTAINER=inv015-bench
printf 'case\tassertion\texpected\tactual\tresult\n' >"$ASSERTIONS"; printf 'case\tmetric\tvalue\tunit\tnote\n' >"$OBSERVATIONS"; printf 'case\tresult\tdetails\n' >"$SUMMARY"
hash_file(){ if command -v sha256sum >/dev/null; then sha256sum "$1"|awk '{print $1}'; else shasum -a 256 "$1"|awk '{print $1}'; fi; }; hash_stdin(){ if command -v sha256sum >/dev/null; then sha256sum|awk '{print $1}'; else shasum -a 256|awk '{print $1}'; fi; }; fingerprint(){ { find "$PROTO" -type f|sort; printf '%s\n' "$ROOT_DIR/run-bench.sh"; }|while IFS= read -r f; do printf '%s  %s\n' "$(hash_file "$f")" "${f#$ROOT_DIR/}"; done|hash_stdin; }
now_ns(){ perl -MTime::HiRes=time -e 'printf "%.0f\n",time()*1000000000'; }; assert_eq(){ local c="$1" a="$2" e="$3" v="$4" r=fail; [[ "$e" == "$v" ]]&&r=pass; printf '%s\t%s\t%s\t%s\t%s\n' "$c" "$a" "$e" "$v" "$r" >>"$ASSERTIONS"; }; observe(){ printf '%s\t%s\t%s\t%s\t%s\n' "$1" "$2" "$3" "$4" "${5:-}" >>"$OBSERVATIONS"; }; finish_case(){ local c="$1" n; n="$(awk -F '\t' -v c="$c" 'NR>1&&$1==c&&$5!="pass"{n++}END{print n+0}' "$ASSERTIONS")"; [[ "$n" == 0 ]]&&printf '%s\tpass\tall assertions passed\n' "$c" >>"$SUMMARY"||printf '%s\tfail\t%s assertion(s) failed\n' "$c" "$n" >>"$SUMMARY"; }
cleanup(){ docker rm -f "$CONTAINER" inv015-oom >/dev/null 2>&1||true; }; trap cleanup EXIT; cleanup
docker build --pull=false -t "$IMAGE" "$PROTO" >"$RESULTS_DIR/docker-build.log"

# Warm-up and repeated in-container architecture benchmarks.
docker run --rm "$IMAGE" --mode=benchmark --iterations=10 >"$RESULTS_DIR/benchmark-raw.tsv"
assert_eq benchmark_matrix ingestion_shapes 3 "$(awk -F '\t' '$1=="ingestion"{a[$2]=1}END{print length(a)}' "$RESULTS_DIR/benchmark-raw.tsv")"
assert_eq benchmark_matrix cardinality_shapes 4 "$(awk -F '\t' '$1=="cardinality"{a[$2]=1}END{print length(a)}' "$RESULTS_DIR/benchmark-raw.tsv")"
assert_eq benchmark_matrix concurrency_shapes 4 "$(awk -F '\t' '$1=="concurrent_scrape"{a[$2]=1}END{print length(a)}' "$RESULTS_DIR/benchmark-raw.tsv")"
assert_eq benchmark_matrix file_detection_modes 3 "$(awk -F '\t' '$1=="file_detection"{a[$2]=1}END{print length(a)}' "$RESULTS_DIR/benchmark-raw.tsv")"
printf 'section\tshape\tmetric\tsamples\tp50\tp95\tp99\tunit\n' >"$RESULTS_DIR/benchmark-summary.tsv"
awk -F '\t' 'NR>1{print $1"\t"$2"\t"$4"\t"$6}' "$RESULTS_DIR/benchmark-raw.tsv"|sort -u|while IFS=$'\t' read -r section shape metric unit; do
  values="$RESULTS_DIR/.values"; awk -F '\t' -v s="$section" -v h="$shape" -v m="$metric" '$1==s&&$2==h&&$4==m{print $5}' "$RESULTS_DIR/benchmark-raw.tsv"|sort -n >"$values"; n="$(wc -l <"$values"|tr -d ' ')"; p50="$(awk -v n="$n" 'NR==int((n-1)*.50)+1{print;exit}' "$values")"; p95="$(awk -v n="$n" 'NR==int((n-1)*.95)+1{print;exit}' "$values")"; p99="$(awk -v n="$n" 'NR==int((n-1)*.99)+1{print;exit}' "$values")"; printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$section" "$shape" "$metric" "$n" "$p50" "$p95" "$p99" "$unit" >>"$RESULTS_DIR/benchmark-summary.tsv"
done; rm -f "$RESULTS_DIR/.values"

# Startup distribution includes container creation, port publication and readiness.
printf 'iteration\tready_latency_ns\n' >"$RESULTS_DIR/startup.tsv"
for i in $(seq 1 10); do cleanup; started="$(now_ns)"; docker run -d --name "$CONTAINER" -p 127.0.0.1::19115 "$IMAGE" --series=1000 >/dev/null; port="$(docker port "$CONTAINER" 19115/tcp|sed 's/.*://')"; for _ in $(seq 1 200); do curl -fsS "http://127.0.0.1:$port/healthz" >/dev/null 2>&1&&break;sleep .01;done; finished="$(now_ns)"; printf '%s\t%s\n' "$i" "$((finished-started))" >>"$RESULTS_DIR/startup.tsv"; docker stop -t 3 "$CONTAINER" >/dev/null; docker rm "$CONTAINER" >/dev/null; done
assert_eq startup iterations 10 "$(($(wc -l <"$RESULTS_DIR/startup.tsv")-1))"

# Idle resources and descriptors.
docker run -d --name "$CONTAINER" --memory=128m --ulimit nofile=256:256 -p 127.0.0.1::19115 "$IMAGE" --series=1000 >/dev/null; PORT="$(docker port "$CONTAINER" 19115/tcp|sed 's/.*://')"; BASE="http://127.0.0.1:$PORT"; for _ in $(seq 1 100);do curl -fsS "$BASE/healthz" >/dev/null 2>&1&&break;sleep .02;done
printf 'sample\tcpu_percent\tmemory_usage\topen_fds\n' >"$RESULTS_DIR/idle.tsv"; for i in $(seq 1 10);do stats="$(docker stats --no-stream --format '{{.CPUPerc}}\t{{.MemUsage}}' "$CONTAINER")"; fds="$(docker exec "$CONTAINER" sh -c 'ls /proc/1/fd | wc -l')"; printf '%s\t%s\t%s\t%s\n' "$i" "$(printf '%s' "$stats"|cut -f1)" "$(printf '%s' "$stats"|cut -f2)" "$fds" >>"$RESULTS_DIR/idle.tsv"; sleep .2;done; assert_eq idle samples 10 "$(($(wc -l <"$RESULTS_DIR/idle.tsv")-1))"

# External complete-snapshot replacement, cardinality and concurrent scrape checks.
seq 1 100|xargs -P16 -I{} curl -fsS -X PUT "$BASE/generate?series=100&generation={}" -o /dev/null
curl -fsS "$BASE/metrics" >"$RESULTS_DIR/after-concurrent-publish.metrics"; series_count="$(grep -c '^inv015_series{' "$RESULTS_DIR/after-concurrent-publish.metrics")"; generations="$(sed -n 's/.*generation="\([^"]*\)".*/\1/p' "$RESULTS_DIR/after-concurrent-publish.metrics"|sort -u|wc -l|tr -d ' ')"; assert_eq replacement complete_series 100 "$series_count"; assert_eq replacement one_generation 1 "$generations"
printf 'series\tbytes\tscrape_ns\n' >"$RESULTS_DIR/cardinality-http.tsv"; for n in 100 1000 10000 100000;do curl -fsS -X PUT "$BASE/generate?series=$n&generation=cardinality" -o /dev/null; started="$(now_ns)";curl -fsS "$BASE/metrics" -o "$RESULTS_DIR/scrape-$n.txt";finished="$(now_ns)";printf '%s\t%s\t%s\n' "$n" "$(wc -c <"$RESULTS_DIR/scrape-$n.txt"|tr -d ' ')" "$((finished-started))" >>"$RESULTS_DIR/cardinality-http.tsv";done
started="$(now_ns)";seq 1 10|xargs -P10 -I{} curl -fsS "$BASE/metrics" -o /dev/null;finished="$(now_ns)";observe concurrent_scrape_10 wall_ns "$((finished-started))" ns;assert_eq concurrent_scrape_10 all_success 0 "$?"

# Queue saturation is measured explicitly rather than inferred from throughput.
export BASE RESULTS_DIR; seq 1 12|xargs -P12 -I{} sh -c 'printf "%s\n" "$(curl -sS -o /dev/null -w "%{http_code}" -X PUT -H "X-Research-Hold-Millis: 400" "$BASE/generate?series=100&generation={}")" >"$RESULTS_DIR/queue-{}.code"'; busy="$(grep -l '^429$' "$RESULTS_DIR"/queue-*.code|wc -l|tr -d ' ')";cat "$RESULTS_DIR"/queue-*.code|sort|uniq -c >"$RESULTS_DIR/queue-summary.txt";rm -f "$RESULTS_DIR"/queue-*.code;assert_eq queue_overflow rejected true "$([[ "$busy" -gt 0 ]]&&echo true||echo false)"

# Malformed candidate and retained last-valid complete snapshot.
printf 'valid 7\n' >"$RESULTS_DIR/valid.snapshot";curl -fsS -X PUT --data-binary @"$RESULTS_DIR/valid.snapshot" "$BASE/snapshot" -o /dev/null;printf 'broken{ 1\n' >"$RESULTS_DIR/malformed.snapshot";code="$(curl -sS -o /dev/null -w '%{http_code}' -X PUT --data-binary @"$RESULTS_DIR/malformed.snapshot" "$BASE/snapshot")";curl -fsS "$BASE/metrics" >"$RESULTS_DIR/after-malformed.metrics";assert_eq failure_injection malformed_400 400 "$code";assert_eq failure_injection last_valid_retained true "$(grep -q '^valid 7$' "$RESULTS_DIR/after-malformed.metrics"&&echo true||echo false)"

# Graceful drain: an in-flight delayed scrape completes before docker stop returns.
curl -fsS -H 'X-Research-Hold-Millis: 800' "$BASE/metrics" -o "$RESULTS_DIR/drain.metrics" & curl_pid=$!;sleep .1;started="$(now_ns)";docker stop -t 3 "$CONTAINER" >/dev/null;finished="$(now_ns)";wait "$curl_pid";drain_code=$?;observe shutdown drain_stop_ns "$((finished-started))" ns;assert_eq shutdown in_flight_completed 0 "$drain_code";docker rm "$CONTAINER" >/dev/null

# Final scrape wait, abort and timeout are executed here, not delegated.
docker run -d --name "$CONTAINER" -p 127.0.0.1::19115 "$IMAGE" --series=1000 --required-scrapes=1 --wait=10s >/dev/null;PORT="$(docker port "$CONTAINER" 19115/tcp|sed 's/.*://')";BASE="http://127.0.0.1:$PORT";for _ in $(seq 1 100);do curl -fsS "$BASE/healthz" >/dev/null 2>&1&&break;sleep .02;done;for _ in $(seq 1 5);do curl -fsS "$BASE/healthz" >/dev/null;done;running="$(docker inspect "$CONTAINER" -f '{{.State.Running}}')";assert_eq final_scrape health_not_counted true "$running";curl -fsS "$BASE/metrics" >"$RESULTS_DIR/final-one.metrics";code="$(docker wait "$CONTAINER")";docker logs "$CONTAINER" >"$RESULTS_DIR/final-one.log" 2>&1;assert_eq final_scrape complete_response_exits 0 "$code";assert_eq final_scrape count_one true "$(grep -q 'final scrapes=1 required=1' "$RESULTS_DIR/final-one.log"&&echo true||echo false)";docker rm "$CONTAINER" >/dev/null

docker run -d --name "$CONTAINER" -p 127.0.0.1::19115 "$IMAGE" --series=100000 --required-scrapes=1 --wait=15s --chunk-delay=1ms >/dev/null;PORT="$(docker port "$CONTAINER" 19115/tcp|sed 's/.*://')";BASE="http://127.0.0.1:$PORT";for _ in $(seq 1 100);do curl -fsS "$BASE/healthz" >/dev/null 2>&1&&break;sleep .02;done;(exec 3<>"/dev/tcp/127.0.0.1/$PORT";printf 'GET /metrics HTTP/1.1\r\nHost:x\r\n\r\n' >&3;sleep .01;exec 3>&-)||true;sleep .3;running="$(docker inspect "$CONTAINER" -f '{{.State.Running}}')";assert_eq aborted_final_scrape still_waiting true "$running";curl -fsS "$BASE/metrics" -o "$RESULTS_DIR/final-large.metrics";code="$(docker wait "$CONTAINER")";assert_eq aborted_final_scrape later_complete_exits 0 "$code";docker logs "$CONTAINER" >"$RESULTS_DIR/final-abort.log" 2>&1;docker rm "$CONTAINER" >/dev/null

docker run -d --name "$CONTAINER" -p 127.0.0.1::19115 "$IMAGE" --series=100 --required-scrapes=1 --wait=500ms >/dev/null;code="$(docker wait "$CONTAINER")";docker logs "$CONTAINER" >"$RESULTS_DIR/final-timeout.log" 2>&1;assert_eq final_timeout exit 0 "$code";assert_eq final_timeout zero_scrapes true "$(grep -q 'final scrapes=0 required=1' "$RESULTS_DIR/final-timeout.log"&&echo true||echo false)";docker rm "$CONTAINER" >/dev/null

bind_code=0;docker run --rm "$IMAGE" --addr=bad >"$RESULTS_DIR/bind-failure.log" 2>&1||bind_code=$?;assert_eq failure_injection bind_exit 70 "$bind_code"
oom_code=0;docker run --name inv015-oom --memory=32m --memory-swap=32m "$IMAGE" --mode=allocate --allocate-bytes=134217728 >"$RESULTS_DIR/oom.log" 2>&1||oom_code=$?;oom="$(docker inspect inv015-oom -f '{{.State.OOMKilled}}')";assert_eq resource_exhaustion oom true "$oom";assert_eq resource_exhaustion exit_137 137 "$oom_code";docker rm inv015-oom >/dev/null

for c in benchmark_matrix startup idle replacement concurrent_scrape_10 queue_overflow failure_injection shutdown final_scrape aborted_final_scrape final_timeout resource_exhaustion;do finish_case "$c";done
{
printf 'key\tvalue\n';printf 'investigation\tINV-015\n';printf 'run_date_utc\t%s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)";printf 'repository_head_sha\t%s\n' "$(git -C "$REPO_DIR" rev-parse HEAD)";printf 'benchmark_scope_diff_clean\t%s\n' "$(git -C "$REPO_DIR" diff --quiet -- research/INV-015/prototype research/INV-015/run-bench.sh&&git -C "$REPO_DIR" diff --cached --quiet -- research/INV-015/prototype research/INV-015/run-bench.sh&&echo true||echo false)";printf 'benchmark_code_fingerprint_sha256\t%s\n' "$(fingerprint)";printf 'host_uname\t%s\n' "$(uname -a|tr '\t\n' ' ')";printf 'host_load\t%s\n' "$(uptime|tr '\t\n' ' ')";printf 'host_cpu_count\t%s\n' "$(sysctl -n hw.ncpu 2>/dev/null||getconf _NPROCESSORS_ONLN)";printf 'host_memory_bytes\t%s\n' "$(sysctl -n hw.memsize 2>/dev/null||echo unknown)";printf 'docker_server_version\t%s\n' "$(docker version --format '{{.Server.Version}}')";printf 'docker_architecture\t%s\n' "$(docker info --format '{{.Architecture}}')";printf 'container_kernel\t%s\n' "$(docker run --rm alpine:3.20 uname -a)";printf 'container_go_version\t%s\n' "$(docker run --rm --entrypoint /bin/sh golang:1.23-alpine -c 'go version')";printf 'benchmark_iterations\t10\n';
}>"$RESULTS_DIR/environment.tsv";printf '%s\n' "$RESULTS_DIR">"$ROOT_DIR/latest-results.txt";failed="$(awk -F '\t' 'NR>1&&$5!="pass"{n++}END{print n+0}' "$ASSERTIONS")";printf 'failed_assertions\t%s\nresults_dir\t%s\n' "$failed" "$RESULTS_DIR">"$RESULTS_DIR/run-summary.tsv";[[ "$failed" == 0 ]]
